### ISSUE TITLE
Inconsistent PV naming

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lcls-plc-tmo-vac#24]
All other PLC IOCs use prefixes like:
PLC:LFE:VAC

But this one is just:
TMO:VAC

Making it more difficult to design screens that work generically on PLC IOCs

**Comment by slacAdpai** [comment]
@ZLLentz  Which PLC ioc are you looking at? The make file has been updated to PLC:TMO:VAC.

**Comment by klauer** [comment]
I spent a bit of time looking around at the PVs here, and it seems that the overall IOC-level prefix (`Makefile`-defined) may be fine (`PLC:TMO:VAC`) but the fast fault and PMPS interface - pytmc pragma-defined differs.

For consistency, you'd expect that if `PLC:TMO:VAC:.*`  exists normally that the PMPS PVs would share the same prefix.

**Comment by slacAdpai** [comment]
@klauer  thanks, I'll go make the changes at the next pamm.

**Comment by ZLLentz** [comment]
Yes, exactly. Sorry for not being more explicit in the issue, I was making 6 similar issues on several repos at the time and didn't come back to update.
